# argocd/apps/electionpulse-wb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: electionpulse-wb
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wasim0028/ElectionPulse-WB.git
    targetRevision: main
    path: deployment/kubernetes/base

  destination:
    server: https://kubernetes.default.svc
    namespace: election

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
